### ISSUE TITLE
Code does not compile in JDK 1.8 anymore.

### ISSUE THREAD

**Issue by RichardHightower** [boonproject/boon#200]
looks like some of your unsafe stuff has changed
huh
            [ERROR] /Users/gcc/Source/boon/src/main/java/org/boon/Ok.java:[51,27] error: incomparable types: Number and int
            [ERROR] /Users/gcc/Source/boon/src/main/java/org/boon/cache/SimpleConcurrentCache.java:[332,27] error: cannot find symbol

[ERROR] symbol:   class Hashing

[ERROR] location: package sun.misc
yeah sun.misc.Hashing is not on the classpath
